### ISSUE TITLE
Error: Can't Apply Message of Uknown Type

### ISSUE THREAD

**Issue by jelling** [ueberdosis/tiptap-collab-replit#1]
## Steps to reproduce

1. branch repo
2. `npm i`
3. `npm run dev`
4. input app id and secret
5. these values are not automatically applied so refresh the browser page

## What happens

- page says it's connected to the collab cloud
- but throws console error "Error: Can't Apply Message of Uknown Type"
- documents do not sync

![Screen Shot 2024-01-06 at 9 17 14 AM](https://github.com/ueberdosis/tiptap-collab-replit/assets/1887486/410c982b-e3c0-40ac-9df4-427c5e8bc5a3)

However, the same key values do work on the Replit:

![Screen Shot 2024-01-06 at 9 30 22 AM](https://github.com/ueberdosis/tiptap-collab-replit/assets/1887486/c4001655-da6b-4df4-8c17-5caea7542e3f)

Note: no changes to have been made to the repo code running locally.

**Comment by janthurau** [comment]
Thanks! This is fixed by https://github.com/ueberdosis/tiptap-collab-replit/commit/9532746aaff26f21aa6cfc634138c678ced135a6.
